[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MeroLagani"
authors = [{name = "Aamosh Maharjan", email = "aamoshmaharjan234@gmail.com"}]
dynamic = ["version", "description"]
